# Generated by Django 5.0.6 on 2024-07-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="slug"
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/blog/picture",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликованно"),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Просмотры"),
                ),
            ],
        ),
    ]
