# Generated by Django 5.0.6 on 2024-07-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("title", "content"),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
