# Generated by Django 5.0.6 on 2024-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now=True, verbose_name="Дата создания"),
        ),
    ]
