# Generated by Django 4.2.2 on 2024-09-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price"),
                "permissions": [
                    ("can_edit_published", "Can edit is_published"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
